name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: install node_modules
      run: |
        cd example/RNBackgroundExample/
        yarn install --frozen-lockfile

    - name: detox setup
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Android build
      run: |
        cd example/RNBackgroundExample/
        yarn deploy/debug/android

