name: React Native iOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  react-native-ios:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Setup Detox
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Install node_modules & deploy
      working-directory: example/RNBackgroundExample/
      run: |
        yarn install --frozen-lockfile
        yarn deploy/release/ios

    - name: iOS test
      working-directory: example/RNBackgroundExample/
      timeout-minutes: 10
      run: |
        npx detox clean-framework-cache && npx detox build-framework-cache
        yarn e2e/test/ios
